### ISSUE TITLE
Remove python dependency

### ISSUE THREAD

**Issue by rejuvyesh** [rejuvyesh/MLFlowLogger.jl#3]
mlflow has a REST API and we should be able directly use it instead of depending on the python client.

**Comment by itan1** [comment]
I would like to add a `MLFlowBackend` to [FluxTraining](https://github.com/FluxML/FluxTraining.jl). In FluxTraining there's already a [TensorBoardBackend](https://github.com/FluxML/FluxTraining.jl/blob/master/src/callbacks/logging/tensorboard.jl) that uses [TBLogger](https://github.com/JuliaLogging/TensorBoardLogger.jl). I would like to follow the same approach and use the `MLFLogger` from this repository.

In the process I can take on this issue and refactor `MLFLogger` in this repository to use the REST API from [MLFlowClient](https://github.com/JuliaAI/MLFlowClient.jl) instead of the Python API.

Before I start, do you have any wishes for the design that I should take into account? If not, I'll just get started and submit a PR next week.

**Comment by rejuvyesh** [comment]
Closed with #5
